* Bandit
** Introduction
This is a writeup for the overthewire.org war game. The password for each 
level is stored in a file named banditX.txt where X is the level number. Then 
use

#+BEGIN_SRC bash

sshpass -p `cat banditX.txt` ssh banditX@bandit.labs.overthewire.org -p 2220

#+END_SRC

to log in.

** Level 0
The password for this level is given: bandit0. Simply connect to the server with SSH to port 2220. 
The password for the next level is stored in a file called readme.

#+BEGIN_SRC bash

bandit0@bandit:~$ ls
readme
bandit0@bandit:~$ cat readme
boJ9jbbUNNfktd78OOpsqOltutMc3MY1

#+END_SRC

** Level 1
The password to the next level is located in a file named '-', to cat out the
contents of this file use the full path to the file from the home directory.

#+BEGIN_SRC bash

bandit1@bandit:~$ ls
-
bandit1@bandit:~$ cat ~/-
CV1DtqXWVFXTvM2F0k09SHz0YwRINYA9

#+END_SRC 

** Level 2
The password is in a file with spaces in the name. To cat out the contents either 
use backslashes before the spaces or surround the entire file name with single 
or double quotes.

 #+BEGIN_SRC 
 
bandit2@bandit:~$ ls -al
total 24
drwxr-xr-x  2 root    root    4096 May  7  2020 .
drwxr-xr-x 41 root    root    4096 May  7  2020 ..
-rw-r--r--  1 root    root     220 May 15  2017 .bash_logout
-rw-r--r--  1 root    root    3526 May 15  2017 .bashrc
-rw-r--r--  1 root    root     675 May 15  2017 .profile
-rw-r-----  1 bandit3 bandit2   33 May  7  2020 spaces in this filename
bandit2@bandit:~$ cat spaces\ in\ this\ filename
UmHadQclWmgdLOKQ3YNgjWxGoRMb5luK

 #+END_SRC
 
** Level 3
The password is in a hidden file inside the directory 'inhere'. To cat out the 
contents move into the inhere directory and cat out the file.

#+BEGIN_SRC 

bandit3@bandit:~$ ls -al
total 24
drwxr-xr-x  3 root root 4096 May  7  2020 .
drwxr-xr-x 41 root root 4096 May  7  2020 ..
-rw-r--r--  1 root root  220 May 15  2017 .bash_logout
-rw-r--r--  1 root root 3526 May 15  2017 .bashrc
drwxr-xr-x  2 root root 4096 May  7  2020 inhere
-rw-r--r--  1 root root  675 May 15  2017 .profile
bandit3@bandit:~$ cd inhere/
bandit3@bandit:~/inhere$ ls -al
total 12
drwxr-xr-x 2 root    root    4096 May  7  2020 .
drwxr-xr-x 3 root    root    4096 May  7  2020 ..
-rw-r----- 1 bandit4 bandit3   33 May  7  2020 .hidden
bandit3@bandit:~/inhere$ cat .hidden
pIwrPrtPN36QITSp3EQaw936yaFoFgAB

#+END_SRC

** Level 4
The password is the only human readable file inside the directory 'inhere'. When
listing all the files in the directory notice that the file names start with a
'-', which means that to use the files as input to a command it requires the full
path from the home directory to be able to execute the command.
To find the file that contains human readable content use the command 'file' and
the regular expression * to execute the command on all files inside the 
directory.

#+BEGIN_SRC 

bandit4@bandit:~$ ls -al
total 24
drwxr-xr-x  3 root root 4096 May  7  2020 .
drwxr-xr-x 41 root root 4096 May  7  2020 ..
-rw-r--r--  1 root root  220 May 15  2017 .bash_logout
-rw-r--r--  1 root root 3526 May 15  2017 .bashrc
drwxr-xr-x  2 root root 4096 May  7  2020 inhere
-rw-r--r--  1 root root  675 May 15  2017 .profile
bandit4@bandit:~$ ls -al inhere/
total 48
drwxr-xr-x 2 root    root    4096 May  7  2020 .
drwxr-xr-x 3 root    root    4096 May  7  2020 ..
-rw-r----- 1 bandit5 bandit4   33 May  7  2020 -file00
-rw-r----- 1 bandit5 bandit4   33 May  7  2020 -file01
-rw-r----- 1 bandit5 bandit4   33 May  7  2020 -file02
-rw-r----- 1 bandit5 bandit4   33 May  7  2020 -file03
-rw-r----- 1 bandit5 bandit4   33 May  7  2020 -file04
-rw-r----- 1 bandit5 bandit4   33 May  7  2020 -file05
-rw-r----- 1 bandit5 bandit4   33 May  7  2020 -file06
-rw-r----- 1 bandit5 bandit4   33 May  7  2020 -file07
-rw-r----- 1 bandit5 bandit4   33 May  7  2020 -file08
-rw-r----- 1 bandit5 bandit4   33 May  7  2020 -file09
bandit4@bandit:~$ file inhere/-file0*
inhere/-file00: data
inhere/-file01: data
inhere/-file02: data
inhere/-file03: data
inhere/-file04: data
inhere/-file05: data
inhere/-file06: data
inhere/-file07: ASCII text
inhere/-file08: data
inhere/-file09: data
bandit4@bandit:~$ cat inhere/-file07
koReBOKuIDDepwhWk7jZC0RTdopnAYKh

#+END_SRC

** Level 5
The directory 'inhere' contains several directories which contains files. One 
of these files contains the password, this file has the following properties:
size = 1033 bytes, is human-readable and is not executable. 
The find command can be used to find this file. The size flag can be used to 
find files of a specific size and the perm flag in conjunction with the \! 
operator can be used to find files that are not executable. To find the files 
that contain human readable text the exec flag can be used to execute the file 
command just like in level 4. Lastly pipe the result of find into grep with the 
text ASCII to find all files that satisfy the required conditions.

#+BEGIN_SRC 

bandit5@bandit:~$ ls -Al
total 16
-rw-r--r--  1 root root     220 May 15  2017 .bash_logout
-rw-r--r--  1 root root    3526 May 15  2017 .bashrc
drwxr-x--- 22 root bandit5 4096 May  7  2020 inhere
-rw-r--r--  1 root root     675 May 15  2017 .profile
bandit5@bandit:~$ ls -Al inhere/
total 80
drwxr-x--- 2 root bandit5 4096 May  7  2020 maybehere00
drwxr-x--- 2 root bandit5 4096 May  7  2020 maybehere01
drwxr-x--- 2 root bandit5 4096 May  7  2020 maybehere02
drwxr-x--- 2 root bandit5 4096 May  7  2020 maybehere03
drwxr-x--- 2 root bandit5 4096 May  7  2020 maybehere04
drwxr-x--- 2 root bandit5 4096 May  7  2020 maybehere05
drwxr-x--- 2 root bandit5 4096 May  7  2020 maybehere06
drwxr-x--- 2 root bandit5 4096 May  7  2020 maybehere07
drwxr-x--- 2 root bandit5 4096 May  7  2020 maybehere08
drwxr-x--- 2 root bandit5 4096 May  7  2020 maybehere09
drwxr-x--- 2 root bandit5 4096 May  7  2020 maybehere10
drwxr-x--- 2 root bandit5 4096 May  7  2020 maybehere11
drwxr-x--- 2 root bandit5 4096 May  7  2020 maybehere12
drwxr-x--- 2 root bandit5 4096 May  7  2020 maybehere13
drwxr-x--- 2 root bandit5 4096 May  7  2020 maybehere14
drwxr-x--- 2 root bandit5 4096 May  7  2020 maybehere15
drwxr-x--- 2 root bandit5 4096 May  7  2020 maybehere16
drwxr-x--- 2 root bandit5 4096 May  7  2020 maybehere17
drwxr-x--- 2 root bandit5 4096 May  7  2020 maybehere18
drwxr-x--- 2 root bandit5 4096 May  7  2020 maybehere19
bandit5@bandit:~$ find ~/inhere/ -size 1033c \! -perm /a+x -exec file {} + | grep ASCII
/home/bandit5/inhere/maybehere07/.file2: ASCII text, with very long lines
bandit5@bandit:~$ cat ~/inhere/maybehere07/.file2
DXjZPULLxYr17uwoI01bNLQbtFemEgo7

#+END_SRC

** Level 6
The file containing the password is somewhere on the server with the following
properties: size = 33 bytes, owned by user bandit7 and owned by group bandit6.
To clean up the 'permission denied' in output from this command redirect the
stderr to /dev/null with '2> /dev/null'.

#+BEGIN_SRC 

bandit6@bandit:~$ find / -type f -user bandit7 -group bandit6 -size 33c 2> /dev/null
/var/lib/dpkg/info/bandit7.password
bandit6@bandit:~$ cat /var/lib/dpkg/info/bandit7.password
HKBPTKQnIay4Fw76bEy8PVxKEDQRKTzs

#+END_SRC

** Level 7
The password is in the file 'data.txt' next to the word millionth. Grep can be
used to find the line that contains that word.

#+BEGIN_SRC 

bandit7@bandit:~$ ls -Al
total 4100
-rw-r--r-- 1 root    root        220 May 15  2017 .bash_logout
-rw-r--r-- 1 root    root       3526 May 15  2017 .bashrc
-rw-r----- 1 bandit8 bandit7 4184396 May  7  2020 data.txt
-rw-r--r-- 1 root    root        675 May 15  2017 .profile
bandit7@bandit:~$ grep millionth data.txt
millionth	cvX2JJa4CFALtqS87jk27qwqGhBM9plV

#+END_SRC

** Level 8
The password is in the file 'data.txt' and is the line that only occurs once in
the file. Uniq -u can filter out all duplicate lines that are adjacent. To find
the only unique line in the text the input must first be sorted with sort.

#+BEGIN_SRC 

bandit8@bandit:~$ ls -Al
total 48
-rw-r--r-- 1 root    root      220 May 15  2017 .bash_logout
-rw-r--r-- 1 root    root     3526 May 15  2017 .bashrc
-rw-r----- 1 bandit9 bandit8 33033 May  7  2020 data.txt
-rw-r--r-- 1 root    root      675 May 15  2017 .profile
bandit8@bandit:~$ sort data.txt | uniq -u
UsvVyFSfZZWbi6wgC7dAFyFuR6jQQUhR

#+END_SRC

** Level 9
The password for the next level is stored in the file data.txt in one of the 
few human-readable strings, preceded by several ‘=’ characters.
Strings can be used to print all the human readable characters and grep to
find all the lines that contain one or more '='.

#+BEGIN_SRC 

bandit9@bandit:~$ ls -Al
total 32
-rw-r--r-- 1 root     root      220 May 15  2017 .bash_logout
-rw-r--r-- 1 root     root     3526 May 15  2017 .bashrc
-rw-r----- 1 bandit10 bandit9 19379 May  7  2020 data.txt
-rw-r--r-- 1 root     root      675 May 15  2017 .profile
bandit9@bandit:~$ strings data.txt | grep =
========== the*2i"4
=:G e
========== password
<I=zsGi
Z)========== is
A=|t&E
Zdb=
c^ LAh=3G
*SF=s
&========== truKLdjsbJ5g7yyJ2X2R0o3a5HQJFuLk
S=A.H&^

#+END_SRC

** Level 10
The password for the next level is stored in the file data.txt, which contains 
base64 encoded data.
To decode base64 use the command base64 with the flag -d.

#+BEGIN_SRC 

bandit10@bandit:~$ ls -Al
total 16
-rw-r--r-- 1 root     root      220 May 15  2017 .bash_logout
-rw-r--r-- 1 root     root     3526 May 15  2017 .bashrc
-rw-r----- 1 bandit11 bandit10   69 May  7  2020 data.txt
-rw-r--r-- 1 root     root      675 May 15  2017 .profile
bandit10@bandit:~$ base64 -d data.txt
The password is IFukwKGsFW8MOq3IRFqrxE1hxTNEbUPR

#+END_SRC

** Level 11
The password for the next level is stored in the file data.txt, where all 
lowercase (a-z) and uppercase (A-Z) letters have been rotated by 13 positions.
Tr can be used to translate a set of characters to another set of characters 
and therefore perform a ROT13 algorithm.

#+BEGIN_SRC 

bandit11@bandit:~$ ls -Al
total 16
-rw-r--r-- 1 root     root      220 May 15  2017 .bash_logout
-rw-r--r-- 1 root     root     3526 May 15  2017 .bashrc
-rw-r----- 1 bandit12 bandit11   49 May  7  2020 data.txt
-rw-r--r-- 1 root     root      675 May 15  2017 .profile
bandit11@bandit:~$ cat data.txt | tr [a-zA-Z] [n-za-mN-ZA-M]
The password is 5Te8Y4drgCRfCx8ugdwuEX8KFC6k2EUu

#+END_SRC

** Level 12
The password for the next level is stored in the file data.txt, which is a 
hexdump of a file that has been repeatedly compressed.
To get the password first reverse the hex dump with xxd and then decompress
the file as many times as necessary with the correct tool. To find out which
tool to use, use the file command.

 #+BEGIN_SRC 
 
bandit12@bandit:~$ mkdir /tmp/bandit12dir
bandit12@bandit:~$ cd !$
cd /tmp/bandit12dir
bandit12@bandit:/tmp/bandit12dir$ cp ~/data.txt .

bandit12@bandit:/tmp/bandit12dir$ xxd -r data.txt > out

bandit12@bandit:/tmp/bandit12dir$ file out
out: gzip compressed data, was "data2.bin", last modified: Thu May  7 18:14:30 2020, max compression, from Unix
bandit12@bandit:/tmp/bandit12dir$ mv out out.gz
bandit12@bandit:/tmp/bandit12dir$ gzip -d out.gz
bandit12@bandit:/tmp/bandit12dir$ ls
data.txt  out

bandit12@bandit:/tmp/bandit12dir$ file out
out: bzip2 compressed data, block size = 900k
bandit12@bandit:/tmp/bandit12dir$ mv out out.bz2
bandit12@bandit:/tmp/bandit12dir$ bzip2 -d out.bz2
bandit12@bandit:/tmp/bandit12dir$ ls
data.txt  out

bandit12@bandit:/tmp/bandit12dir$ file out
out: gzip compressed data, was "data4.bin", last modified: Thu May  7 18:14:30 2020, max compression, from Unix
bandit12@bandit:/tmp/bandit12dir$ mv out out.gz
bandit12@bandit:/tmp/bandit12dir$ gzip -d out.gz
bandit12@bandit:/tmp/bandit12dir$ ls
data.txt  out
bandit12@bandit:/tmp/bandit12dir$ file out
out: POSIX tar archive (GNU)

bandit12@bandit:/tmp/bandit12dir$ tar -xf out
bandit12@bandit:/tmp/bandit12dir$ ls
data5.bin  data.txt  out
bandit12@bandit:/tmp/bandit12dir$ file data5.bin
data5.bin: POSIX tar archive (GNU)
bandit12@bandit:/tmp/bandit12dir$ tar -xf data5.bin
bandit12@bandit:/tmp/bandit12dir$ ls
data5.bin  data6.bin  data.txt  out

bandit12@bandit:/tmp/bandit12dir$ file data6.bin
data6.bin: bzip2 compressed data, block size = 900k
bandit12@bandit:/tmp/bandit12dir$ mv data6.bin data.bz2
bandit12@bandit:/tmp/bandit12dir$ bzip2 -d data.bz2
bandit12@bandit:/tmp/bandit12dir$ ls
data  data5.bin  data.txt  out

bandit12@bandit:/tmp/bandit12dir$ file data
data: POSIX tar archive (GNU)
bandit12@bandit:/tmp/bandit12dir$ tar -xf data
bandit12@bandit:/tmp/bandit12dir$ ls
data  data5.bin  data8.bin  data.txt  out

bandit12@bandit:/tmp/bandit12dir$ file data8.bin
data8.bin: gzip compressed data, was "data9.bin", last modified: Thu May  7 18:14:30 2020, max compression, from Unix
bandit12@bandit:/tmp/bandit12dir$ mv data8.bin data.gz
bandit12@bandit:/tmp/bandit12dir$ gzip -d data.gz
gzip: data already exists; do you wish to overwrite (y or n)? y
bandit12@bandit:/tmp/bandit12dir$ ls
data  data5.bin  data.txt  out

bandit12@bandit:/tmp/bandit12dir$ file data
data: ASCII text
bandit12@bandit:/tmp/bandit12dir$ cat data
The password is 8ZjyCRiBWFYkneahHwxCv3wb2a1ORpYL
 #+END_SRC

** Level 13
The password for the next level is stored in /etc/bandit_pass/bandit14 and can 
only be read by user bandit14. For this level, you don’t get the next password, 
but you get a private SSH key that can be used to log into the next level.
To become the bandit14 user use the sshkey.private in the ssh command and 
connect to the localhost as bandit14. Then cat out the password.

#+BEGIN_SRC 

bandit13@bandit:~$ ls
sshkey.private
bandit13@bandit:~$ ssh -i sshkey.private bandit14@localhost
Could not create directory '/home/bandit13/.ssh'.
The authenticity of host 'localhost (127.0.0.1)' can't be established.
ECDSA key fingerprint is SHA256:98UL0ZWr85496EtCRkKlo20X3OPnyPSB5tB5RPbhczc.
Are you sure you want to continue connecting (yes/no)? yes
Failed to add the host to the list of known hosts (/home/bandit13/.ssh/known_hosts).
This is a OverTheWire game server. More information on http://www.overthewire.org/wargames

bandit14@bandit:~$ cat /etc/bandit_pass/bandit14
4wcYUJFw0k0XLShlDzztnTBHiqxU3b3e
#+END_SRC

** Level 14
The password for the next level can be retrieved by submitting the password of 
the current level to port 30000 on localhost.
Use netcat or telnet to connect to the localhost on port 30000 and enter the 
password of level 14.

#+BEGIN_SRC 

bandit14@bandit:~$ nc localhost 30000
4wcYUJFw0k0XLShlDzztnTBHiqxU3b3e
Correct!
BfMYroe26WYalil77FoDi9qh59eK5xNr

#+END_SRC

** Level 15
The password for the next level can be retrieved by submitting the password of 
the current level to port 30001 on localhost using SSL encryption.
Use openssl with s_client to connect to the localhost at port 30001.

#+BEGIN_SRC 

bandit15@bandit:~$ openssl s_client -connect localhost:30001
CONNECTED(00000003)
...
BfMYroe26WYalil77FoDi9qh59eK5xNr
Correct!
cluFn7wTiGryunymYOu4RcffSxQluehd

closed
#+END_SRC

** Level 16
The credentials for the next level can be retrieved by submitting the password 
of the current level to a port on localhost in the range 31000 to 32000. First 
find out which of these ports have a server listening on them. Then find out 
which of those speak SSL and which don’t. There is only 1 server that will give 
the next credentials, the others will simply send back to you whatever you send 
to it.
Use nmap to scan all the port in the range 31000-32000 and use the flag -sV to
check if the port uses SSL. The password for the next level is a RSA key. Store
it in a file with permissions 0400 so it can only be read by the user. And use 
SSH and the private key to login to the server for the next level just like in 
level 13.

#+BEGIN_SRC 

bandit16@bandit:~$ nmap localhost -p 31000-32000 -sV

Starting Nmap 7.40 ( https://nmap.org ) at 2021-12-10 20:03 CET
Nmap scan report for localhost (127.0.0.1)
Host is up (0.00031s latency).
Not shown: 996 closed ports
PORT      STATE SERVICE     VERSION
31046/tcp open  echo
31518/tcp open  ssl/echo
31691/tcp open  echo
31790/tcp open  ssl/unknown
31960/tcp open  echo

bandit16@bandit:~$ openssl s_client -connect localhost:31790
---
cluFn7wTiGryunymYOu4RcffSxQluehd
Correct!
-----BEGIN RSA PRIVATE KEY-----
MIIEogIBAAKCAQEAvmOkuifmMg6HL2YPIOjon6iWfbp7c3jx34YkYWqUH57SUdyJ
imZzeyGC0gtZPGujUSxiJSWI/oTqexh+cAMTSMlOJf7+BrJObArnxd9Y7YT2bRPQ
Ja6Lzb558YW3FZl87ORiO+rW4LCDCNd2lUvLE/GL2GWyuKN0K5iCd5TbtJzEkQTu
DSt2mcNn4rhAL+JFr56o4T6z8WWAW18BR6yGrMq7Q/kALHYW3OekePQAzL0VUYbW
JGTi65CxbCnzc/w4+mqQyvmzpWtMAzJTzAzQxNbkR2MBGySxDLrjg0LWN6sK7wNX
x0YVztz/zbIkPjfkU1jHS+9EbVNj+D1XFOJuaQIDAQABAoIBABagpxpM1aoLWfvD
KHcj10nqcoBc4oE11aFYQwik7xfW+24pRNuDE6SFthOar69jp5RlLwD1NhPx3iBl
J9nOM8OJ0VToum43UOS8YxF8WwhXriYGnc1sskbwpXOUDc9uX4+UESzH22P29ovd
d8WErY0gPxun8pbJLmxkAtWNhpMvfe0050vk9TL5wqbu9AlbssgTcCXkMQnPw9nC
YNN6DDP2lbcBrvgT9YCNL6C+ZKufD52yOQ9qOkwFTEQpjtF4uNtJom+asvlpmS8A
vLY9r60wYSvmZhNqBUrj7lyCtXMIu1kkd4w7F77k+DjHoAXyxcUp1DGL51sOmama
+TOWWgECgYEA8JtPxP0GRJ+IQkX262jM3dEIkza8ky5moIwUqYdsx0NxHgRRhORT
8c8hAuRBb2G82so8vUHk/fur85OEfc9TncnCY2crpoqsghifKLxrLgtT+qDpfZnx
SatLdt8GfQ85yA7hnWWJ2MxF3NaeSDm75Lsm+tBbAiyc9P2jGRNtMSkCgYEAypHd
HCctNi/FwjulhttFx/rHYKhLidZDFYeiE/v45bN4yFm8x7R/b0iE7KaszX+Exdvt
SghaTdcG0Knyw1bpJVyusavPzpaJMjdJ6tcFhVAbAjm7enCIvGCSx+X3l5SiWg0A
R57hJglezIiVjv3aGwHwvlZvtszK6zV6oXFAu0ECgYAbjo46T4hyP5tJi93V5HDi
Ttiek7xRVxUl+iU7rWkGAXFpMLFteQEsRr7PJ/lemmEY5eTDAFMLy9FL2m9oQWCg
R8VdwSk8r9FGLS+9aKcV5PI/WEKlwgXinB3OhYimtiG2Cg5JCqIZFHxD6MjEGOiu
L8ktHMPvodBwNsSBULpG0QKBgBAplTfC1HOnWiMGOU3KPwYWt0O6CdTkmJOmL8Ni
blh9elyZ9FsGxsgtRBXRsqXuz7wtsQAgLHxbdLq/ZJQ7YfzOKU4ZxEnabvXnvWkU
YOdjHdSOoKvDQNWu6ucyLRAWFuISeXw9a/9p7ftpxm0TSgyvmfLF2MIAEwyzRqaM
77pBAoGAMmjmIJdjp+Ez8duyn3ieo36yrttF5NSsJLAbxFpdlc1gvtGCWW+9Cq0b
dxviW8+TFVEBl1O4f7HVm6EpTscdDxU+bCXWkfjuRb7Dy9GOtt9JPsX8MBTakzh3
vBgsyi/sN3RqRBcGU40fOoZyfAMT8s1m/uYv52O6IgeuZ/ujbjY=
-----END RSA PRIVATE KEY-----

closed

#+END_SRC

** Level 17
There are 2 files in the homedirectory: passwords.old and passwords.new. The 
password for the next level is in passwords.new and is the only line that has 
been changed between passwords.old and passwords.new
Using the diff command without flags will give the changed line.

#+BEGIN_SRC 

bandit17@bandit:~$ ls -Al
total 28
-rw-r----- 1 bandit17 bandit17   33 Jul 11  2020 .bandit16.password
-rw-r--r-- 1 root     root      220 May 15  2017 .bash_logout
-rw-r--r-- 1 root     root     3526 May 15  2017 .bashrc
-rw-r----- 1 bandit18 bandit17 3300 May  7  2020 passwords.new
-rw-r----- 1 bandit18 bandit17 3300 May  7  2020 passwords.old
-rw-r--r-- 1 root     root      675 May 15  2017 .profile
drwxr-xr-x 2 root     root     4096 Jul 11  2020 .ssh
bandit17@bandit:~$ diff passwords.new passwords.old
42c42
< kfBf3eYk5BPBRzwjqutbbfE887SVc5Yd
---
> w0Yfolrc5bwjS4qw5mq1nnQi6mF03bii
#+END_SRC

Meaning kfBf3eYk5BPBRzwjqutbbfE887SVc5Yd is the password for level 18.

** Level 18
The password for the next level is stored in a file readme in the homedirectory. 
Unfortunately, someone has modified .bashrc to log you out when you log in with 
SSH.
To execute a command immediately after connecting to the remote server give the
ssh command the flag -o (stands for option, and allows for adding utility that
is not covered by the flags, such as executing a command remotely), followed by 
RemoteCommand="some command" where some commmand is the desired command.

#+BEGIN_SRC 

bryan@xps:~/overthewire$ sshpass -p `cat bandit18.txt` ssh bandit18@bandit.labs.overthewire.org -p 2220 -o RemoteCommand="cat readme"
This is a OverTheWire game server. More information on http://www.overthewire.org/wargames

IueksS7Ubh8G3DCwVzrTd8rAVOwq3M5x

#+END_SRC

** Level 19
